package com.mycompany.grading.system;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class Attendance extends javax.swing.JFrame {

    /**
     * Creates new form Attendance
     */
    public Attendance() {
        initComponents();
        listAll();
    }
private void listAll() {
    // Database connection parameters
    String url = "jdbc:mysql://localhost:3306/my_gradingsystem";
    String username = "root";
    String password = "22703380";

    try (Connection connection = DriverManager.getConnection(url, username, password)) {
        System.out.println("Connected to the database!");

        // Query to fetch all fish data
        String query = "SELECT * FROM attendance";
        try (PreparedStatement statement = connection.prepareStatement(query);
             ResultSet resultSet = statement.executeQuery()) {

            // Clear existing table data
            DefaultTableModel model = (DefaultTableModel) att_table.getModel();
            model.setRowCount(0);

            // Populate the table with data from the database
            while (resultSet.next()) {
                Object[] row = {
                    resultSet.getInt("att_id"),
                    resultSet.getInt("crs_id"),
                    resultSet.getInt("std_id"),
                    resultSet.getDate("att_date")
                };
                model.addRow(row);
            }
        }
    } catch (SQLException ex) {
        System.err.println("Database connection error: " + ex.getMessage());
        ex.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        txt_grd_id = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        txt_grd_id2 = new javax.swing.JTextField();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        txt_grd_id1 = new javax.swing.JTextField();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel14 = new javax.swing.JLabel();
        txt_grd_id7 = new javax.swing.JTextField();
        txt_grd_id8 = new javax.swing.JTextField();
        txt_grd_id9 = new javax.swing.JTextField();
        txt_grd_id10 = new javax.swing.JTextField();
        txt_grd_id11 = new javax.swing.JTextField();
        txt_grd_id12 = new javax.swing.JTextField();
        txt_grd_id13 = new javax.swing.JTextField();
        btn_add_dept = new javax.swing.JButton();
        btn_delete_dept = new javax.swing.JButton();
        btn_clear_dept = new javax.swing.JButton();
        btn_backup_dept = new javax.swing.JButton();
        btn_delAll_dept = new javax.swing.JButton();
        btn_restoreAll_dept = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        txt_std_id = new javax.swing.JTextField();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        txt_crs_id = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        att_table = new javax.swing.JTable();
        btn_add_att = new javax.swing.JButton();
        btn_delete_att = new javax.swing.JButton();
        btn_clear_att = new javax.swing.JButton();
        btn_backup_att = new javax.swing.JButton();
        btn_delAll_att = new javax.swing.JButton();
        btn_restoreAll_att = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        btn_edit = new javax.swing.JButton();

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Grade ID");
        jLabel1.setToolTipText("");

        txt_grd_id.setToolTipText("");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student ID");

        txt_grd_id2.setToolTipText("");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Course ID");

        txt_grd_id1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(33, 33, 33));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Grade ID");
        jLabel8.setToolTipText("");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Course ID");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Student ID");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("MT");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("F");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("HW");
        jLabel13.setToolTipText("");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Letter Grade");
        jLabel14.setToolTipText("");

        txt_grd_id7.setToolTipText("");

        txt_grd_id8.setToolTipText("");

        txt_grd_id9.setToolTipText("");

        txt_grd_id10.setToolTipText("");

        txt_grd_id11.setToolTipText("");

        txt_grd_id12.setToolTipText("");

        txt_grd_id13.setToolTipText("");

        btn_add_dept.setBackground(new java.awt.Color(76, 175, 80));
        btn_add_dept.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_dept.setText("Add");

        btn_delete_dept.setBackground(new java.awt.Color(244, 67, 54));
        btn_delete_dept.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete_dept.setText("Delete");
        btn_delete_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_deptActionPerformed(evt);
            }
        });

        btn_clear_dept.setBackground(new java.awt.Color(33, 150, 243));
        btn_clear_dept.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear_dept.setText("Clear");
        btn_clear_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear_deptActionPerformed(evt);
            }
        });

        btn_backup_dept.setBackground(new java.awt.Color(255, 152, 0));
        btn_backup_dept.setForeground(new java.awt.Color(255, 255, 255));
        btn_backup_dept.setText("Backup");

        btn_delAll_dept.setBackground(new java.awt.Color(211, 47, 47));
        btn_delAll_dept.setForeground(new java.awt.Color(255, 255, 255));
        btn_delAll_dept.setText("Delete All");

        btn_restoreAll_dept.setBackground(new java.awt.Color(139, 195, 74));
        btn_restoreAll_dept.setForeground(new java.awt.Color(255, 255, 255));
        btn_restoreAll_dept.setText("Restore All");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "grdID", "stdID", "crsID", "MT", "HW", "F", "Letter"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_clear_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_delAll_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_restoreAll_dept, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(btn_backup_dept, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_delete_dept, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(64, 64, 64))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_add_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt_grd_id10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_grd_id12))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_grd_id9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(txt_grd_id8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(txt_grd_id11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(txt_grd_id13)))
                                    .addComponent(txt_grd_id7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_grd_id7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_grd_id9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_grd_id8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_grd_id10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_grd_id12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_grd_id11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_grd_id13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_add_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_delete_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_clear_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_backup_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_delAll_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_restoreAll_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student ID");

        txt_std_id.setToolTipText("");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Course ID");

        txt_crs_id.setToolTipText("");
        txt_crs_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_crs_idActionPerformed(evt);
            }
        });

        txt_date.setToolTipText("");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date");
        jLabel7.setToolTipText("");

        att_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AttID", "crsID", "stdID", "Date"
            }
        ));
        jScrollPane1.setViewportView(att_table);

        btn_add_att.setBackground(new java.awt.Color(76, 175, 80));
        btn_add_att.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_att.setText("Add");
        btn_add_att.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_attActionPerformed(evt);
            }
        });

        btn_delete_att.setBackground(new java.awt.Color(244, 67, 54));
        btn_delete_att.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete_att.setText("Delete");
        btn_delete_att.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_attActionPerformed(evt);
            }
        });

        btn_clear_att.setBackground(new java.awt.Color(33, 150, 243));
        btn_clear_att.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear_att.setText("Clear");
        btn_clear_att.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear_attActionPerformed(evt);
            }
        });

        btn_backup_att.setBackground(new java.awt.Color(255, 152, 0));
        btn_backup_att.setForeground(new java.awt.Color(255, 255, 255));
        btn_backup_att.setText("Backup");
        btn_backup_att.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backup_attActionPerformed(evt);
            }
        });

        btn_delAll_att.setBackground(new java.awt.Color(211, 47, 47));
        btn_delAll_att.setForeground(new java.awt.Color(255, 255, 255));
        btn_delAll_att.setText("Delete All");
        btn_delAll_att.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delAll_attActionPerformed(evt);
            }
        });

        btn_restoreAll_att.setBackground(new java.awt.Color(139, 195, 74));
        btn_restoreAll_att.setForeground(new java.awt.Color(255, 255, 255));
        btn_restoreAll_att.setText("Restore All");
        btn_restoreAll_att.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restoreAll_attActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Attendance");

        btn_edit.setBackground(new java.awt.Color(102, 0, 102));
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_add_att, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_clear_att, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_delete_att, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(btn_backup_att, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_restoreAll_att, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_delAll_att, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(txt_std_id, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(txt_crs_id, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_std_id, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_crs_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_delete_att, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_add_att, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_backup_att, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_clear_att, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_restoreAll_att, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delAll_att, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_delete_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_delete_deptActionPerformed

    private void btn_clear_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clear_deptActionPerformed

    private void btn_clear_attActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear_attActionPerformed
        // TODO add your handling code here:
        txt_std_id.setText("");
        txt_crs_id.setText("");
        txt_date.setText("");
    }//GEN-LAST:event_btn_clear_attActionPerformed

    private void btn_delete_attActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_attActionPerformed
        // TODO add your handling code here:
int row = att_table.getSelectedRow(); // Get the selected row index
    if (row >= 0) { 
        DefaultTableModel model = (DefaultTableModel) att_table.getModel();
        int id = (int) model.getValueAt(row, 0); 
        int confirmation = JOptionPane.showConfirmDialog(null,
                "Are you sure you want to delete this record?",
                "Delete Confirmation",
                JOptionPane.YES_NO_OPTION);

        if (confirmation == JOptionPane.YES_OPTION) {
            String url = "jdbc:mysql://localhost:3306/my_gradingsystem";
            String username = "root";
            String password = "22703380";

            try (Connection connection = DriverManager.getConnection(url, username, password)) {
                System.out.println("Connected to the database!");

                  GradingSystem.Attendance.deleteAttendanceById(id, connection);
                listAll();
            } catch (SQLException ex) {
                System.err.println("Database connection error: " + ex.getMessage());
                ex.printStackTrace();
            }
        }
    } else {
        // Display a message if no row is selected
        JOptionPane.showMessageDialog(null, "Please select a row to delete.");
    }

    }//GEN-LAST:event_btn_delete_attActionPerformed

    private void txt_crs_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_crs_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_crs_idActionPerformed

    private void btn_add_attActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_attActionPerformed
        // TODO add your handling code here:
        int crs_id = Integer.parseInt(txt_crs_id.getText());
        int std_id =Integer.parseInt(txt_std_id.getText());
        
        String inputdate = txt_date.getText();

        java.sql.Date date = GradingSystem.format_Date(inputdate);

        if (date == null) {
            JOptionPane.showMessageDialog(null, "Invalid date format. Please use dd/MM/yyyy.");
            return; // Exit if the date is invalid
        }
               String url = "jdbc:mysql://localhost:3306/my_gradingsystem";
            String username = "root";
            String password = "22703380";
            
        try (Connection connection = DriverManager.getConnection(url, username, password)) {
            System.out.println("Connected to the database!");
            GradingSystem.Attendance.addAttendance(std_id, crs_id, date, connection);
            listAll();
           
        } catch (SQLException ex) {
            System.err.println("Database connection error: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error while adding student: " + ex.getMessage());
        }

        
        txt_std_id.setText("");
        txt_crs_id.setText("");
        txt_date.setText("");
    }//GEN-LAST:event_btn_add_attActionPerformed
public static java.sql.Date format_Date(String date) {
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy"); // Adjust format as needed
    dateFormat.setLenient(false); // Strict date validation
    java.sql.Date sqlDate = null;

    try {
        // Parse the date and convert to java.sql.Date
        java.util.Date parsedDate = dateFormat.parse(date);
        sqlDate = new java.sql.Date(parsedDate.getTime());
    } catch (Exception e) {
        System.err.println("Invalid date format: " + date);
        e.printStackTrace();
    }

    return sqlDate;
}

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        int row = att_table.getSelectedRow(); // Get the selected row index
        DefaultTableModel model = (DefaultTableModel) att_table.getModel();
        int id = (int) model.getValueAt(row, 0);

         int crs_id = Integer.parseInt(txt_crs_id.getText());
        int std_id =Integer.parseInt(txt_std_id.getText());
        
        String inputdate = txt_date.getText();

        java.sql.Date date = GradingSystem.format_Date(inputdate);

        if (date == null) {
            JOptionPane.showMessageDialog(null, "Invalid date format. Please use dd/MM/yyyy.");
            return; // Exit if the date is invalid
        }
               String url = "jdbc:mysql://localhost:3306/my_gradingsystem";
            String username = "root";
            String password = "22703380";
            
        try (Connection connection = DriverManager.getConnection(url, username, password)) {
            System.out.println("Connected to the database!");
            GradingSystem.Attendance.editAttendance(id, std_id, crs_id, date, connection);
            listAll();
            
        } catch (SQLException ex) {
            System.err.println("Database connection error: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, "Error while adding student: " + ex.getMessage());
        }

        
        txt_std_id.setText("");
        txt_crs_id.setText("");
        txt_date.setText("");
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_delAll_attActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delAll_attActionPerformed

            String url = "jdbc:mysql://localhost:3306/my_gradingsystem";
            String username = "root";
            String password = "22703380";

            try (Connection connection = DriverManager.getConnection(url, username, password)) {
                System.out.println("Connected to the database!");

                  GradingSystem.Attendance.deleteAllAttendance(connection);
                listAll();
            } catch (SQLException ex) {
                System.err.println("Database connection error: " + ex.getMessage());
                ex.printStackTrace();
            
        }
    }//GEN-LAST:event_btn_delAll_attActionPerformed

    private void btn_restoreAll_attActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restoreAll_attActionPerformed
        // TODO add your handling code here:
           String url = "jdbc:mysql://localhost:3306/my_gradingsystem";
            String username = "root";
            String password = "22703380";

            try (Connection connection = DriverManager.getConnection(url, username, password)) {
                System.out.println("Connected to the database!");

                  GradingSystem.Attendance.restoreAttendance(connection);
                listAll();
            } catch (SQLException ex) {
                System.err.println("Database connection error: " + ex.getMessage());
                ex.printStackTrace();
            
        }
    }//GEN-LAST:event_btn_restoreAll_attActionPerformed

    private void btn_backup_attActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backup_attActionPerformed
        // TODO add your handling code here:
           String url = "jdbc:mysql://localhost:3306/my_gradingsystem";
            String username = "root";
            String password = "22703380";

            try (Connection connection = DriverManager.getConnection(url, username, password)) {
                System.out.println("Connected to the database!");

                  GradingSystem.Attendance.backupAttendance(connection);
                listAll();
            } catch (SQLException ex) {
                System.err.println("Database connection error: " + ex.getMessage());
                ex.printStackTrace();
            
        }
    }//GEN-LAST:event_btn_backup_attActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable att_table;
    private javax.swing.JButton btn_add_att;
    private javax.swing.JButton btn_add_dept;
    private javax.swing.JButton btn_backup_att;
    private javax.swing.JButton btn_backup_dept;
    private javax.swing.JButton btn_clear_att;
    private javax.swing.JButton btn_clear_dept;
    private javax.swing.JButton btn_delAll_att;
    private javax.swing.JButton btn_delAll_dept;
    private javax.swing.JButton btn_delete_att;
    private javax.swing.JButton btn_delete_dept;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_restoreAll_att;
    private javax.swing.JButton btn_restoreAll_dept;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txt_crs_id;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_grd_id;
    private javax.swing.JTextField txt_grd_id1;
    private javax.swing.JTextField txt_grd_id10;
    private javax.swing.JTextField txt_grd_id11;
    private javax.swing.JTextField txt_grd_id12;
    private javax.swing.JTextField txt_grd_id13;
    private javax.swing.JTextField txt_grd_id2;
    private javax.swing.JTextField txt_grd_id7;
    private javax.swing.JTextField txt_grd_id8;
    private javax.swing.JTextField txt_grd_id9;
    private javax.swing.JTextField txt_std_id;
    // End of variables declaration//GEN-END:variables
}
